# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-05 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flow',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
