# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-05 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20160605_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='flow',
            name='target_ip',
            field=models.GenericIPAddressField(default='12.12.12.12'),
            preserve_default=False,
        ),
    ]
