version: '2'
services:
  ipdiag:
    build: ipdiag
    ports:
      - '5000'
  users:
    build: users
    ports:
      - '5000'
  aggregate:
    build: aggregate
    ports:
      - '5000'
    links:
      - ipdiag
      - users
networks:
  default:
    driver: ovs
