version: '2'
services:
  ipdiag:
    image: mkwm/siuu-tip-ipdiag
    ports:
      - '5000'
  users:
    image: mkwm/siuu-tip-users
    ports:
      - '5000'
  aggregate:
    image: mkwm/siuu-tip-aggregate
    ports:
      - '5000'
    environment:
      USERS_URL: http://users:5000/
      IPDIAG_URL: http://ipdiag:5000/
networks:
  default:
    external:
      name: suutip
