version: '2'
services:
  ipdiag:
    image: mkwm/siuu-tip-ipdiag
    ports:
      - '5000'
    restart: always
  users:
    depends_on:
      - db
    image: mkwm/siuu-tip-users
    ports:
      - '5000'
    environment:
      DB_CONNECT_STRING: 'postgresql+psycopg2://users:${DB_POSTGRES_PASSWORD}@db:5432/users'
    entrypoint: ['/usr/local/bin/wait-for-it.sh', 'db:5432', '-t', '0', '--']
    command: ['python', 'users.py', '--host', '0.0.0.0']
    restart: always
  aggregate:
    depends_on:
      - ipdiag
      - users
    image: mkwm/siuu-tip-aggregate
    ports:
      - '5000'
    environment:
      USERS_URL: http://users:5000
      IPDIAG_URL: http://ipdiag:5000
    restart: always
  gui:
    depends_on:
      - ipdiag
      - users
      - aggregate
    image: mkwm/siuu-tip-gui
    ports:
      - '3001'
    environment:
      USERS_URL: /api/users/
      IPDIAG_URL: /api/ipdiag/
      AGGREGATE_URL: /api/aggregate/
    restart: always
  db:
    image: postgres:9.5
    ports:
      - '5432'
    environment:
      POSTGRES_USER: users
      POSTGRES_PASSWORD: '${DB_POSTGRES_PASSWORD}'
    volumes:
      - '/var/lib/docker/cluster-volumes/db-pgdata:/var/lib/postgresql/data'
    restart: always
networks:
  default:
    external:
      name: suutip
