version: '2'
services:
  ipdiag:
    image: mkwm/siuu-tip-ipdiag
    ports:
      - '5000'
  users:
    image: mkwm/siuu-tip-users
    ports:
      - '5000'
  aggregate:
    image: mkwm/siuu-tip-aggregate
    ports:
      - '5000'
    environment:
      USERS_URL: http://users:5000
      IPDIAG_URL: http://ipdiag:5000
  gui:
    image: mkwm/siuu-tip-gui
    ports:
      - '3001'
    environment:
      USERS_URL: /api/users/
      IPDIAG_URL: /api/ipdiag/
      AGGREGATE_URL: /api/aggregate/
networks:
  default:
    external:
      name: suutip
